---
- name: Install Apache
  dnf:
    name: httpd
    state: present

- name: Start Apache service
  systemd:
    name: httpd
    enabled: yes
    state: started

- name: Install firewalld
  dnf:
    name: firewalld
    state: present

- name: Start firewalld service
  systemd:
    name: firewalld
    enabled: yes
    state: started

- name: Permit HTTP
  ansible.posix.firewalld:
    service: http
    permanent: yes
    state: enabled
    immediate: yes

- name: Create a Hello World page
  template:
    src: web_content.j2
    dest: /var/www/html/index.html
